ansible_user: admin
ansible_password: cisco123
ansible_network_os: ios
ansible_connection: network_cli
ansible_ssh_common_args: >-
  -o KexAlgorithms=+diffie-hellman-group14-sha1
  -o HostKeyAlgorithms=+ssh-rsa
  -o PubkeyAcceptedKeyTypes=+ssh-rsa
  -o StrictHostKeyChecking=no
ansible_ssh_executable: /usr/bin/ssh
